language: r
r:
- release
- devel
os:
- linux
- osx
matrix:
  exclude:
  - r: devel
    os: osx
sudo: false
cache: packages
r_github_packages:
- statnet/statnet.common
- statnet/network
- statnet/networkDynamic
- statnet/ergm-private@dev
- statnet/ergm.multi-private@dev
addons:
  apt:
    packages:
      - r-cran-rmpi
warnings_are_errors: false
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual
